### ISSUE TITLE
The callback URL is either absent or incorrect - Wrong port in URL (use 80 or 443)

### ISSUE THREAD

**Issue by oasisck** [mika-nt28/Jeedom-withings#44]
Hi
I'm not using standard web port.
I can't use withing plugin because it force 80 or 443 ?

**Comment by mika-nt28** [comment]
Yes, the URL callback for the notification has restrictions on the Withings API

> Callback URL
> 
> Partner URL called by our system to send notifications through HTTP POST requests. Make sure that your server can handle a HTTP HEAD request called to verify the validity of your url.
> 
> Your URL must :
> 
> be a valid URL, provided as a URL-encoded string. Please refer to w3schools URL encoding reference to learn more about URL encoding.
> not be greater than 255 characters.
> neither contain an IP or 'localhost'. Only port 80 and 443 are allowed.
>
